version: '3.1'

services:
  db:
    image: mysql:8.4
    container_name: nest_db
    restart: unless-stopped
    environment:
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=music_player
    ports:
      - "5102:3306"
    volumes:
      - dbdata:/db/mysql

volumes:
  dbdata: